#Thanks TZAPU. https://tzapu.com/automate-arduino-ide-esp8266-build-testing-travisci/
language: c
before_install:
  - "/sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz
  - tar xf arduino-1.8.9-linux64.tar.xz
  - sudo mv arduino-1.8.9 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
# boards manager not working on 1.6.7 - 1.6.8
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
  - arduino --board esp8266:esp8266:generic:xtal=80,vt=flash,exception=disabled,ResetMethod=ck,CrystalFreq=26,FlashFreq=40,FlashMode=dout,eesz=512K,led=2,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200 --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
  - arduino --verify --verbose $PWD/AutoGarden_WebServer.ino
script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
#notifications:
#  email:
#    on_success: change
#    on_failure: change
